language: python
python:
    - 2.7.6

before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential python-dev python-pip libxml2-dev libxslt1-dev cython
    - sudo pip install cython stix

script:
    - python setup.py build
    - python setup.py test

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - /^release-.*$/