language: python
python:
    - 2.7.6

before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential python-dev python-pip libxml2-dev libxslt1-dev cython
    - sudo pip install stix

install:
    - git clone --depth=50 --branch=master git://github.com/csirtgadgets/py-cif-sdk.git py-cif-sdk
    - cd py-cif-sdk
    - python setup.py install
    - cd ../
    #- pip install -r requirements.txt

script:
    - python setup.py build
    - python setup.py test

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - /^release-.*$/